### ISSUE TITLE
perms

### ISSUE THREAD

**Issue by GreekRa** [xSisyphusx/Sisyphus_Nui_Denial#1]
hello,i add the perms in perms lua  and not working.can you give me a example?thanks you

**Comment by MoneSuper** [comment]
![opera_b5JFnic14f](https://github.com/xSisyphusx/Sisyphus_Nui_Denial/assets/62680426/39de967e-3139-4b8b-afaf-936ee03ae375)
I mean its a solid example

**Comment by GreekRa** [comment]
> ![opera_b5JFnic14f](https://user-images.githubusercontent.com/62680426/251207882-39de967e-3139-4b8b-afaf-936ee03ae375.png) I mean its a solid example

Yes i replace the xxxx with license or discord but nothing happen and take again ban😂

**Comment by TheMajorMayhem** [comment]
> > ![opera_b5JFnic14f](https://user-images.githubusercontent.com/62680426/251207882-39de967e-3139-4b8b-afaf-936ee03ae375.png) I mean its a solid example
> 
> Yes i replace the xxxx with license or discord but nothing happen and take again ban😂

Hello, @GreekRa - I have gone back to try to replicate this issue, but I am not having any problems with this function. Could you provide any error codes that you may be receiving, if any? 

I will attempt to find some time to make a more in depth example in the README.

**Comment by GreekRa** [comment]
> > > ![opera_b5JFnic14f](https://user-images.githubusercontent.com/62680426/251207882-39de967e-3139-4b8b-afaf-936ee03ae375.png) I mean its a solid example
> > 
> > 
> > Yes i replace the xxxx with license or discord but nothing happen and take again ban😂
> 
> Hello, @GreekRa - I have gone back to try to replicate this issue, but I am not having any problems with this function. Could you provide any error codes that you may be receiving, if any?
> 
> I will attempt to find some time to make a more in depth example in the README.

Thank you for reply.. No take any error or something. The script works perfect, just something maybe happens with perm or I'm not add correct the perms.
